<?xml version="1.0" encoding="utf-8"?><Database Name="tin415de2171609" Class="MyArtDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=den1.mssql7.gear.host;Initial Catalog=tin415de2171609;Persist Security Info=True;User ID=tin415de2171609" SettingsObjectName="TIN415DE01_HomeworkW03.Properties.Settings" SettingsPropertyName="tin415de2171609ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Art_Materials_n_Tools" Member="Art_Materials_n_Tools">
    <Type Name="Art_Materials_n_Tool">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Category" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>